version: '3'

services:
  db:
    image: postgres:12
    #environment:
    #  - POSTGRES_DB=postgres
    #  - POSTGRES_USER=postgres
    #  - POSTGRES_PASSWORD=postgres
    env_file:
      - .env
    volumes:
     - pg_data:/var/lib/postgresql/data
    networks:
      - djangonetwork

  backend:
    build: .
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - .env
    depends_on:
      - db
   
    networks:
      - djangonetwork

 

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - backend
    networks:
      - djangonetwork
    restart: always

volumes:
  static_volume:
  pg_data:


networks:
  djangonetwork:
    driver: bridge