# Generated by Django 4.1.3 on 2023-05-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueApp', '0002_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createissue',
            name='issue_description',
            field=models.TextField(),
        ),
    ]
