# Generated by Django 4.1.3 on 2024-08-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueApp', '0003_teaminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
