# Generated by Django 4.1.3 on 2024-08-17 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueApp', '0004_teaminvitation_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 6, 56, 8, 383545, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
