# Generated by Django 4.1.3 on 2024-08-17 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueApp', '0005_teaminvitation_expires_at_teaminvitation_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 6, 56, 58, 599812, tzinfo=datetime.timezone.utc)),
        ),
    ]
