# Generated by Django 4.1.3 on 2024-08-17 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueApp', '0007_alter_teaminvitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 17, 7, 26, 43, 465543, tzinfo=datetime.timezone.utc)),
        ),
    ]
