# Generated by Django 4.1.3 on 2024-08-19 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueApp', '0008_alter_teaminvitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 14, 20, 24, 127536, tzinfo=datetime.timezone.utc)),
        ),
    ]
