apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: issue-app-data
          persistentVolumeClaim:
            claimName: django-app-pvc
      containers:
<<<<<<< HEAD
        - image: wanjirumurira/issue_nginx:latest
=======
        - image: wanjirumurira/issue_nginx
>>>>>>> 0f1f972d06eff35480856ffaa0921553c7b7667e
          name: nginx
          ports:
            - containerPort: 80
              name: proxy
          volumeMounts:
            - name: issue-app-data
              mountPath: /home/app/web/staticfiles
          resources:
            limits:
              cpu: "0.25"  # Maximum of 0.5 CPU cores
              memory: "512Mi"  # Maximum of 512 MiB memory
